# Generated by Django 3.0.5 on 2020-04-08 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=200)),
                ('specify', models.CharField(max_length=50)),
                ('manifest', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('draft_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.draft')),
            ],
            bases=('app.draft',),
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('draft_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.draft')),
            ],
            bases=('app.draft',),
        ),
    ]
